version: '3'

services:

  # init:
  #   build: ./1_init
  #   volumes:
  #     - ./1_init:/usr/src/app
  #   depends_on:
  #     - ganache

  asset-tracker:
    build: ./ContractService
    volumes:
      - ./ContractService:/usr/src/app
    ports:
      - 5001:80
    depends_on:
      - ganache

  ganache:
    build: ./ganache
    volumes:
      - ./ganache:/usr/src/app
    ports:
      - 8545:8545
