version: '3'

services:

  config:
    build: ./config_manager
    volumes:
      - ./config_manager:/usr/src/app
    ports:
      - 5100:80

  init:
    build: ./1_init
    volumes:
      - ./1_init:/usr/src/app
    depends_on:
      - ganache
      - config

  asset-tracker:
    build: ./ContractService
    volumes:
      - ./ContractService:/usr/src/app
    ports:
      - 5001:80
    depends_on:
      - ganache
      - init

  ganache:
    build: ./ganache
    volumes:
      - ./ganache:/usr/src/app
    ports:
      - 8545:8545
